export const ITI_CONSIGNMENT_STOCKTAKE_CLEAR_SCANNED_PACKS =
  'ITI_CONSIGNMENT_STOCKTAKE_CLEAR_SCANNED_PACKS';
export const ITI_CONSIGNMENT_STOCKTAKE_DELETE_SCANNED_PACK =
  'ITI_CONSIGNMENT_STOCKTAKE_DELETE_SCANNED_PACK';
export const ITI_CONSIGNMENT_STOCKTAKE_ADD_SCANNED_PACK =
  'ITI_CONSIGNMENT_STOCKTAKE_ADD_SCANNED_PACK';
export const ITI_CONSIGNMENT_STOCKTAKE_SET_SITE =
  'ITI_CONSIGNMENT_STOCKTAKE_SET_SITE';
export const ITI_CONSIGNMENT_STOCKTAKE_SET_PACKETS =
  'ITI_CONSIGNMENT_STOCKTAKE_SET_PACKETS';
export const ITI_CONSIGNMENT_STOCKTAKE_SET_OPERATIONS =
  'ITI_CONSIGNMENT_STOCKTAKE_SET_OPERATIONS';
export const ITI_CONSIGNMENT_STOCKTAKE_SET_OPERATION =
  'ITI_CONSIGNMENT_STOCKTAKE_SET_OPERATION';
export const ITI_CONSIGNMENT_STOCKTAKE_SET_PO =
  'ITI_CONSIGNMENT_STOCKTAKE_SET_PO';
export const ITI_CONSIGNMENT_STOCKTAKE_GET_SITES =
  'ITI_CONSIGNMENT_STOCKTAKE_GET_SITES';
export const ITI_CONSIGNMENT_STOCKTAKE_GET_SITES_SUCCESS =
  'ITI_CONSIGNMENT_STOCKTAKE_GET_SITES_SUCCESS';
export const ITI_CONSIGNMENT_STOCKTAKE_GET_SITES_ERROR =
  'ITI_CONSIGNMENT_STOCKTAKE_GET_SITES_ERROR';
