import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  cardStyle: { backgroundColor: 'white' },
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    paddingRight: 10,
    paddingLeft: 10,
    paddingTop: 0,
    paddingBottom: 5,
    alignContent: 'center',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  packDetailsContainer: {
    padding: 5,
    marginRight: 2,
    marginLeft: 2,
    marginTop: 0,
    marginBottom: 0,
  },
  packOptionsContainer: {
    paddingLeft: 10,
    paddingTop: 10,
    flex: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    // borderColor: 'black', borderWidth: 1,
  },
  dropDownContainer: {
    borderWidth: 0,
    borderColor: 'black',
    // width: 100,
    // paddingTop: 5,
    // paddingBottom: 5,
    paddingLeft: 5,
    paddingRight: 5,
    // verticalAlign: 'bottom',
  },
  wideButtonStyle: {
    borderRadius: 10,
    width: '100%',
  },
  splitPackDetailsContainer: {
    padding: 5,
    marginRight: 2,
    marginLeft: 2,
    marginTop: 5,
    marginBottom: 0,
  },
  addSplitSubmitButtonStyle: {
    width: 70,
    alignSelf: 'stretch',
    marginBottom: 30,
    marginRight: 4,
  },
  splitCountInputStyle: {
    borderWidth: 0,
    borderColor: 'black',
    width: 200,
    // paddingTop: 15,
    // paddingBottom: 5,
    paddingLeft: 5,
    paddingRight: 5,
    flex: 1,
    // verticalAlign: 'bottom',
  },
  innerContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignContent: 'center',
  },
  loginLoadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shortButton: {
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: '#3498db',
    borderWidth: 1,
    borderColor: 'red',
    padding: 10,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 5,
    marginRight: 5,
  },
  buttonStyle: {
    borderRadius: 10,
    width: 200,
  },
  buttonContainerStyle: {
    // flex: 0,
    alignItems: 'center',
    // paddingHorizontal: 50,
    // borderWidth: 1,
    // borderColor: 'black',
    // borderStyle: 'solid',
    marginTop: 5,
    marginLeft: 5,
    marginRight: 5,
    marginBottom: 5,
  },
  rightSwipeItem: {
    // borderWidth: 1,
    // borderColor: 'black',
    // borderStyle: 'solid',
    flex: 1,
    flexDirection: 'column',
    // justifyContent: 'flex-start',
    justifyContent: 'center',
    // alignItems: 'flex-end',
    paddingLeft: 20,
  },
  leftSwipeItem: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingRight: 20,
  },
  listItem: {
    height: 75,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanInputContainer: {
    flex: 0,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  logo: {
    alignSelf: 'center',
    marginBottom: 40,
    marginTop: 10,
  },
  input: {
    // fontSize: 30,
    // paddingTop: 30,
    // textAlign: 'center',
    marginLeft: 20,
    // borderBottomWidth: 5,
    // borderBottomColor: '#3498db',
  },
  inputContainerStyle: {
    flex: 0,
    alignSelf: 'center',
    marginBottom: 5,
    marginTop: 5,
  },
  titleContainer: {
    flexDirection: 'column',
  },
  titleTextStyle: {
    paddingTop: 8,
    fontSize: 20,
    textAlign: 'left',
    fontWeight: 'bold',
  },
  descriptionTextStyle: {
    paddingTop: 5,
    textAlign: 'left',
  },
  smartScanInputContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
  },
  smartScanListContainer: {
    flex: 1,
    flexDirection: 'column',
    // justifyContent: 'flex-start',
  },
  taskItemContainer: {
    backgroundColor: '#C0C0C0',
    paddingTop: 20,
    paddingBottom: 20,
    paddingLeft: 5,
    paddingRight: 5,
    marginBottom: 5,
    marginTop: 5,
    borderRadius: 5,
  },
  taskItemTitleText: {
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 5,
    paddingRight: 5,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  buttonText: {
    fontSize: 30,
    color: 'white',
  },
  drawerList: {},
  drawerListIcon: {
    width: 27,
  },
  drawerListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 23,
  },
  drawerListItemText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 23,
    paddingLeft: 15,
    flex: 1,
  },
  subtitleView: {
    flexDirection: 'row',
    paddingLeft: 10,
    paddingTop: 5,
  },
  subtitleText: {
    color: 'grey',
  },
});

export const colors = {
  primary: '#3498db',
  secondary: '#ddd',
};

export default styles;
