import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  cardStyle: {backgroundColor: 'white'},
  container: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    paddingRight: 10,
    paddingLeft: 10,
    paddingTop: 0,
    paddingBottom: 5,
    alignContent: 'center',
  },
  innerContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignContent: 'center',
  },
  loginLoadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconStyle: {
    width: 30,
    height: 30,
  },
  shortButton: {
    alignItems: 'center',
    borderRadius: 20,
    backgroundColor: '#3498db',
    borderWidth: 1,
    borderColor: 'red',
    padding: 10,
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 5,
    marginRight: 5,
  },
  buttonStyle: {
    borderRadius: 10,
    width: 200,
  },
  buttonContainerStyle: {
    // flex: 0,
    alignItems: 'center',
    // paddingHorizontal: 50,
    // borderWidth: 1,
    // borderColor: 'black',
    // borderStyle: 'solid',
    marginTop: 5,
    marginLeft: 5,
    marginRight: 5,
    marginBottom: 5,
  },
  // rightSwipeItem: {
  //   // borderWidth: 1,
  //   // borderColor: 'black',
  //   // borderStyle: 'solid',
  //   flex: 1,
  //   flexDirection: 'column',
  //   // justifyContent: 'flex-start',
  //   justifyContent: 'center',
  //   // alignItems: 'flex-end',
  //   paddingLeft: 20,
  // },
  leftSwipeItem: {
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'center',
    paddingRight: 20,
  },
  listItem: {
    height: 75,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scanInputContainer: {
    flex: 0,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  logo: {
    alignSelf: 'center',
    marginBottom: 40,
    marginTop: 10,
  },
  input: {
    // fontSize: 30,
    // paddingTop: 30,
    // textAlign: 'center',
    marginLeft: 20,
    // borderBottomWidth: 5,
    // borderBottomColor: '#3498db',
  },
  inputContainerStyle: {
    flex: 0,
    alignSelf: 'center',
    marginBottom: 5,
    marginTop: 5,
  },
  titleContainer: {
    flexDirection: 'column',
    marginBottom: 10,
    // borderWidth: 1,
    // borderColor: 'red',
  },
  titleTextStyle: {
    paddingTop: 8,
    fontSize: 20,
    textAlign: 'left',
    fontWeight: 'bold',
  },
  descriptionTextStyle: {
    paddingTop: 5,
    textAlign: 'left',
  },
  smartScanInputContainer: {
    flex: 0,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    // borderWidth: 1,
    // borderColor: 'blue',
  },
  smartScanListContainer: {
    flex: 1,
    // borderWidth: 1,
    // borderColor: 'red',
    flexDirection: 'column',
    // justifyContent: 'flex-start',
  },
  taskItemContainer: {
    backgroundColor: '#C0C0C0',
    paddingTop: 20,
    paddingBottom: 20,
    paddingLeft: 5,
    paddingRight: 5,
    marginBottom: 5,
    marginTop: 5,
    borderRadius: 5,
  },
  taskItemTitleText: {
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 5,
    paddingRight: 5,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  buttonText: {
    fontSize: 30,
    color: 'white',
  },
  drawerList: {},
  drawerListIcon: {
    width: 27,
  },
  drawerListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 23,
  },
  drawerListItemText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 23,
    paddingLeft: 15,
    flex: 1,
  },
  subtitleView: {
    // flex: 1,
    flexDirection: 'row',
    // flexWrap: 'wrap',
    // borderColor: 'red',
    // borderStyle: 'solid',
    // borderWidth: 1,
    paddingLeft: 10,
    paddingTop: 5,
  },
  subtitleText: {
    color: 'grey',
    overflow: 'visible',
  },
  rightSwipeItem: {
    // borderWidth: 1,
    // borderColor: 'black',
    // borderStyle: 'solid',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    alignContent: 'center',
    paddingLeft: 10,
  },
});

export const colors = {
  primary: '#3498db',
  secondary: '#ddd',
};

export default styles;
