// @flow
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const UPDATE_USER_INPUT = 'UPDATE_USER_INPUT';
export const UPDATE_PASSWORD_INPUT = 'UPDATE_PASSWORD_INPUT';
export const UPDATE_API_SETTING = 'UPDATE_API_SETTING';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const AUTHENTICATE_USER_ERROR = 'AUTHENTICATE_USER_ERROR';
export const UPDATE_NETWORK_STATUS = 'UPDATE_NETWORK_STATUS';
export const TOGGLE_DEBUG_OPTION = 'TOGGLE_DEBUG_OPTION';
export const UPDATE_DIRECT_NETWORK_STATUS = 'UPDATE_DIRECT_NETWORK_STATUS';
export const SEND_OFFLINE_NETWORK_TEST = 'SEND_OFFLINE_NETWORK_TEST';
export const SEND_OFFLINE_NETWORK_TEST_SUCCESS =
  'SEND_OFFLINE_NETWORK_TEST_SUCCESS';
export const SEND_OFFLINE_NETWORK_TEST_ERROR =
  'SEND_OFFLINE_NETWORK_TEST_ERROR';
export const SEND_API_OFFLINE_NETWORK_TEST = 'SEND_API_OFFLINE_NETWORK_TEST';
export const SEND_API_OFFLINE_NETWORK_TEST_SUCCESS =
  'SEND_API_OFFLINE_NETWORK_TEST_SUCCESS';
export const SEND_API_OFFLINE_NETWORK_TEST_ERROR =
  'SEND_API_OFFLINE_NETWORK_TEST_ERROR';
export const UPDATE_OFFLINE_NETWORK_STATUS = 'UPDATE_OFFLINE_NETWORK_STATUS';
export const UPDATE_API_OFFLINE_NETWORK_STATUS =
  'UPDATE_API_OFFLINE_NETWORK_STATUS';
export const LOGOUT = 'LOGOUT';
export const RESET_STORE = 'RESET_STORE';
export const GET_CLIENT_CONFIGS = 'GET_CLIENT_CONFIGS';
export const GET_CLIENT_CONFIGS_SUCCESS = 'GET_CLIENT_CONFIGS_SUCCESS';
export const GET_CLIENT_CONFIGS_ERROR = 'GET_CLIENT_CONFIGS_ERROR';
export const GET_CLIENT_APPS = 'GET_CLIENT_APPS';
export const GET_CLIENT_APPS_SUCCESS = 'GET_CLIENT_APPS_SUCCESS';
export const GET_CLIENT_APPS_ERROR = 'GET_CLIENT_APPS_ERROR';
export const SEND_SYSTEM_ALERT = 'SEND_SYSTEM_ALERT';
export const IS_RENEWING_TOKEN = 'IS_RENEWING_TOKEN';
export const GET_SITE_ENDPOINTS = 'GET_SITE_ENDPOINTS';
export const GET_SITE_ENDPOINTS_SUCCESS = 'GET_SITE_ENDPOINTS_SUCCESS';
export const GET_SITE_ENDPOINTS_ERROR = 'GET_SITE_ENDPOINTS_ERROR';
export const UPDATE_SELECTED_SITE_ENDPOINT = 'UPDATE_SELECTED_SITE_ENDPOINT';
export const RENEW_TOKEN = 'RENEW_TOKEN';
export const RENEW_TOKEN_SUCCESS = 'RENEW_TOKEN_SUCCESS';
export const RENEW_TOKEN_ERROR = 'RENEW_TOKEN_ERROR';
export const UPDATE_DRAWER_TITLE = 'UPDATE_DRAWER_TITLE';
export const UPDATE_DEVICE_INFO = 'UPDATE_DEVICE_INFO';
export const LOADING_COMPLETE = 'LOADING_COMPLETE';
export const SCHEDULED_5S_TICK = 'SCHEDULED_5S_TICK';
export const SCHEDULED_TICK = 'SCHEDULED_TICK';
export const UPDATE_WEBAPP_URL = 'UPDATE_WEBAPP_URL';
export const UPDATE_SEQ_URL = 'UPDATE_SEQ_URL';
export const UPDATE_SEQ_API = 'UPDATE_SEQ_API';
export const UPDATE_SEQ_LOGGING = 'UPDATE_SEQ_LOGGING';
export const TOGGLE_AUTO_UPDATE = 'TOGGLE_AUTO_UPDATE';
export const TOGGLE_BETA_CHANNEL = 'TOGGLE_BETA_CHANNEL';
export const SET_SHOW_WEBAPP = 'SET_SHOW_WEBAPP';
export const SET_WEBAPP_FULLSCREEN = 'SET_WEBAPP_FULLSCREEN';
export const SET_WEBAPP_REFRESH = 'SET_WEBAPP_REFRESH';
export const SET_WEBAPP_ENABLED = 'SET_WEBAPP_ENABLED';
export const SET_WEBAPP_PRIORITISED = 'SET_WEBAPP_PRIORITISED';
