export const LOADPLANNING_SET_LOAD_INPUT = 'LOADPLANNING_SET_LOAD_INPUT';
export const LOADPLANNING_SET_SCANPACK_INPUT =
  'LOADPLANNING_SET_SCANPACK_INPUT';
export const LOADPLANNING_SET_PACKOPTIONS_INPUT =
  'LOADPLANNING_SET_PACKOPTIONS_INPUT';
export const LOADPLANNING_SET_SPLITCOUNT_INPUT =
  'LOADPLANNING_SET_SPLITCOUNT_INPUT';
export const LOADPLANNING_SET_SPLITPACKLENGTHDROPDOWN_INPUT =
  'LOADPLANNING_SET_SPLITPACKLENGTHDROPDOWN_INPUT';
export const LOADPLANNING_ADD_SPLITPACKSUMMARY =
  'LOADPLANNING_ADD_SPLITPACKSUMMARY';
export const LOADPLANNING_DELETE_SPLITPACKSUMMARY =
  'LOADPLANNING_DELETE_SPLITPACKSUMMARY';
export const LOADPLANNING_GET_LOADS = 'LOADPLANNING_GET_LOADS';
export const LOADPLANNING_GET_LOADS_SUCCESS = 'LOADPLANNING_GET_LOADS_SUCCESS';
export const LOADPLANNING_GET_LOADS_ERROR = 'LOADPLANNING_GET_LOADS_ERROR';
export const LOADPLANNING_GET_LOADITEMS = 'LOADPLANNING_GET_LOADITEMS';
export const LOADPLANNING_GET_LOADITEMS_SUCCESS =
  'LOADPLANNING_GET_LOADITEMS_SUCCESS';
export const LOADPLANNING_GET_LOADITEMS_ERROR =
  'LOADPLANNING_GET_LOADITEMS_ERROR';
export const LOADPLANNING_GET_OFFLINE_LOADS_SUCCESS =
  'LOADPLANNING_GET_OFFLINE_LOADS_SUCCESS';
export const LOADPLANNING_GET_OFFLINE_LOADITEMS_SUCCESS =
  'LOADPLANNING_GET_OFFLINE_LOADITEMS_SUCCESS';
export const LOADPLANNING_GET_CONSIGNMENTITEMS =
  'LOADPLANNING_GET_CONSIGNMENTITEMS';
export const LOADPLANNING_GET_CONSIGNMENTITEMS_SUCCESS =
  'LOADPLANNING_GET_CONSIGNMENTITEMS_SUCCESS';
export const LOADPLANNING_GET_CONSIGNMENTITEMS_ERROR =
  'LOADPLANNING_GET_CONSIGNMENTITEMS_ERROR';
export const LOADPLANNING_RESERVE_PACK = 'LOADPLANNING_RESERVE_PACK';
export const LOADPLANNING_RESERVE_PACK_STUB = 'LOADPLANNING_RESERVE_PACK_STUB';
export const LOADPLANNING_RESERVE_PACK_SUCCESS =
  'LOADPLANNING_RESERVE_PACK_SUCCESS';
export const LOADPLANNING_RESERVE_PACK_ERROR =
  'LOADPLANNING_RESERVE_PACK_ERROR';
export const LOADPLANNING_SPLIT_PACK = 'LOADPLANNING_SPLIT_PACK';
export const LOADPLANNING_SPLIT_PACK_SUCCESS =
  'LOADPLANNING_SPLIT_PACK_SUCCESS';
export const LOADPLANNING_SPLIT_PACK_ERROR = 'LOADPLANNING_SPLIT_PACK_ERROR';
export const LOADPLANNING_GET_SPLITPACKDETAILS =
  'LOADPLANNING_GET_SPLITPACKDETAILS';
export const LOADPLANNING_GET_SPLITPACKDETAILS_SUCCESS =
  'LOADPLANNING_GET_SPLITPACKDETAILS_SUCCESS';
export const LOADPLANNING_GET_SPLITPACKDETAILS_ERROR =
  'LOADPLANNING_GET_SPLITPACKDETAILS_ERROR';
export const LOADPLANNING_UNRESERVE_PACK = 'LOADPLANNING_UNRESERVE_PACK';
export const LOADPLANNING_UNRESERVE_PACK_SUCCESS =
  'LOADPLANNING_UNRESERVE_PACK_SUCCESS';
export const LOADPLANNING_UNRESERVE_PACK_ERROR =
  'LOADPLANNING_UNRESERVE_PACK_ERROR';
export const LOADPLANNING_SAVE_LOADITEMS = 'LOADPLANNING_SAVE_LOADITEMS';
export const LOADPLANNING_CLEAR_LOADITEMS = 'LOADPLANNING_CLEAR_LOADITEMS';
export const LOADPLANNING_SET_PACKLISTOPTIONS_INPUT =
  'LOADPLANNING_SET_PACKLISTOPTIONS_INPUT';
export const LOADPLANNING_GET_CONSIGNMENTPACKS =
  'LOADPLANNING_GET_CONSIGNMENTPACKS';
export const LOADPLANNING_GET_CONSIGNMENTPACKS_SUCCESS =
  'LOADPLANNING_GET_CONSIGNMENTPACKS_SUCCESS';
export const LOADPLANNING_GET_CONSIGNMENTPACKS_ERROR =
  'LOADPLANNING_GET_CONSIGNMENTPACKS_ERROR';
export const LOADPLANNING_GET_CONSIGNMENTRESERVEDPACKS =
  'LOADPLANNING_GET_CONSIGNMENTRESERVEDPACKS';
export const LOADPLANNING_GET_CONSIGNMENTRESERVEDPACKS_SUCCESS =
  'LOADPLANNING_GET_CONSIGNMENTRESERVEDPACKS_SUCCESS';
export const LOADPLANNING_GET_CONSIGNMENTRESERVEDPACKS_ERROR =
  'LOADPLANNING_GET_CONSIGNMENTRESERVEDPACKS_ERROR';
export const LOADPLANNING_GET_WORKSPLITFORMBIN =
  'LOADPLANNING_GET_WORKSPLITFORMBIN';
export const LOADPLANNING_GET_WORKSPLITFORMBIN_SUCCESS =
  'LOADPLANNING_GET_WORKSPLITFORMBIN_SUCCESS';
export const LOADPLANNING_GET_WORKSPLITFORMBIN_ERROR =
  'LOADPLANNING_GET_WORKSPLITFORMBIN_ERROR';
export const LOADPLANNING_ADD_WORKSPLITFORMBIN =
  'LOADPLANNING_ADD_WORKSPLITFORMBIN';
export const LOADPLANNING_ADD_WORKSPLITFORMBIN_SUCCESS =
  'LOADPLANNING_ADD_WORKSPLITFORMBIN_SUCCESS';
export const LOADPLANNING_ADD_WORKSPLITFORMBIN_ERROR =
  'LOADPLANNING_ADD_WORKSPLITFORMBIN_ERROR';
export const LOADPLANNING_DELETE_WORKSPLITFORMBIN =
  'LOADPLANNING_DELETE_WORKSPLITFORMBIN';
export const LOADPLANNING_DELETE_WORKSPLITFORMBIN_SUCCESS =
  'LOADPLANNING_DELETE_WORKSPLITFORMBIN_SUCCESS';
export const LOADPLANNING_DELETE_WORKSPLITFORMBIN_ERROR =
  'LOADPLANNING_DELETE_WORKSPLITFORMBIN_ERROR';
export const LOADPLANNING_GET_VERIFY_PACKS = 'LOADPLANNING_GET_VERIFY_PACKS';
export const LOADPLANNING_GET_VERIFY_PACKS_SUCCESS =
  'LOADPLANNING_GET_VERIFY_PACKS_SUCCESS';
export const LOADPLANNING_GET_VERIFY_PACKS_ERROR =
  'LOADPLANNING_GET_VERIFY_PACKS_ERROR';
export const LOADPLANNING_CLEAR_VERIFY_PACKS =
  'LOADPLANNING_CLEAR_VERIFY_PACKS';
export const LOADPLANNING_SAVE_VERIFY_PACKS = 'LOADPLANNING_SAVE_VERIFY_PACKS';
export const LOADPLANNING_SAVE_UNKNOWN_PACKS =
  'LOADPLANNING_SAVE_UNKNOWN_PACKS';
export const LOADPLANNING_CLEAR_UNKNOWN_PACKS =
  'LOADPLANNING_CLEAR_UNKNOWN_PACKS';
export const LOADPLANNING_POST_VERIFY_PACK = 'LOADPLANNING_POST_VERIFY_PACK';
export const LOADPLANNING_POST_VERIFY_PACK_SUCCESS =
  'LOADPLANNING_POST_VERIFY_PACK_SUCCESS';
export const LOADPLANNING_POST_VERIFY_PACK_ERROR =
  'LOADPLANNING_POST_VERIFY_PACK_ERROR';
export const LOADPLANNING_PURGE_INVALID_CONSIGNMENTITEMS =
  'LOADPLANNING_PURGE_INVALID_CONSIGNMENTITEMS';
