export const PROCESSING_UPDATE_INPUT = 'PROCESSING_UPDATE_INPUT';
export const PROCESSING_CLEAR_MERGEPACKDETAILS = 'PROCESSING_CLEAR_MERGEPACKDETAILS';
export const PROCESSING_GET_MERGEPACKDETAILS = 'PROCESSING_GET_MERGEPACKDETAILS';
export const PROCESSING_GET_MERGEPACKDETAILS_SUCCESS = 'PROCESSING_GET_MERGEPACKDETAILS_SUCCESS';
export const PROCESSING_GET_MERGEPACKDETAILS_ERROR = 'PROCESSING_GET_MERGEPACKDETAILS_ERROR';
export const PROCESSING_MERGEPACKTOBIN = 'PROCESSING_MERGEPACKTOBIN';
export const PROCESSING_MERGEPACKTOBIN_SUCCESS = 'PROCESSING_MERGEPACKTOBIN_SUCCESS';
export const PROCESSING_MERGEPACKTOBIN_ERROR = 'PROCESSING_MERGEPACKTOBIN_ERROR';
