export const QUICKSCAN_GET_TASK_CATEGORIES = 'QUICKSCAN_GET_TASK_CATEGORIES';
export const QUICKSCAN_GET_TASK_CATEGORIES_SUCCESS = 'QUICKSCAN_GET_TASK_CATEGORIES_SUCCESS';
export const QUICKSCAN_GET_TASK_CATEGORIES_ERROR = 'QUICKSCAN_GET_TASK_CATEGORIES_ERROR';

export const QUICKSCAN_GET_TASKS = 'QUICKSCAN_GET_TASKS';
export const QUICKSCAN_GET_TASKS_SUCCESS = 'QUICKSCAN_GET_TASKS_SUCCESS';
export const QUICKSCAN_GET_TASKS_ERROR = 'QUICKSCAN_GET_TASKS_ERROR';

export const QUICKSCAN_ADD_PACK = 'QUICKSCAN_ADD_PACK';
export const QUICKSCAN_REMOVE_PACK = 'QUICKSCAN_REMOVE_PACK';
export const QUICKSCAN_CLEAR_PACK = 'QUICKSCAN_CLEAR_PACK';

export const QUICKSCAN_SEND_ITEM = 'QUICKSCAN_SEND_ITEM';
export const QUICKSCAN_SEND_ITEM_SUCCESS = 'QUICKSCAN_SEND_ITEM_SUCCESS';
export const QUICKSCAN_SEND_ITEM_ERROR = 'QUICKSCAN_SEND_ITEM_ERROR';

export const QUICKSCAN_UPDATE_IS_SYNCING = 'QUICKSCAN_UPDATE_IS_SYNCING';
