export const DYNAFORM_GET_FORMS = 'DYNAFORM_GET_FORMS';
export const DYNAFORM_GET_FORMS_SUCCESS = 'DYNAFORM_GET_FORMS_SUCCESS';
export const DYNAFORM_GET_FORMS_ERROR = 'DYNAFORM_GET_FORMS_ERROR';

export const DYNAFORM_ADD_PAYLOAD = 'DYNAFORM_ADD_PAYLOAD';
export const DYNAFORM_REMOVE_PAYLOAD = 'DYNAFORM_REMOVE_PAYLOAD';

export const DYNAFORM_CLEAR_QUEUE = 'DYNAFORM_CLEAR_QUEUE';

export const DYNAFORM_SEND_ITEM = 'DYNAFORM_SEND_ITEM';
export const DYNAFORM_SEND_ITEM_SUCCESS = 'DYNAFORM_SEND_ITEM_SUCCESS';
export const DYNAFORM_SEND_ITEM_ERROR = 'DYNAFORM_SEND_ITEM_ERROR';

export const DYNAFORM_UPDATE_IS_SYNCING = 'DYNAFORM_UPDATE_IS_SYNCING';
