export const QUICKQUERY_GET_TASKS = 'QUICKQUERY_GET_TASKS';
export const QUICKQUERY_GET_TASKS_SUCCESS = 'QUICKQUERY_GET_TASKS_SUCCESS';
export const QUICKQUERY_GET_TASKS_ERROR = 'QUICKQUERY_GET_TASKS_ERROR';

export const QUICKQUERY_GET_TASK_ACTIONS = 'QUICKQUERY_GET_TASK_ACTIONS';
export const QUICKQUERY_GET_TASK_ACTIONS_SUCCESS =
  'QUICKQUERY_GET_TASK_ACTIONS_SUCCESS';
export const QUICKQUERY_GET_TASK_ACTIONS_ERROR =
  'UICKQUERY_GET_TASK_ACTIONS_ERROR';

// export const QUICKQUERY_ADD_PAYLOAD = 'QUICKQUERY_ADD_PAYLOAD';
// export const QUICKQUERY_REMOVE_PAYLOAD = 'QUICKQUERY_REMOVE_PAYLOAD';

export const QUICKQUERY_CLEAR_CONTEXT = 'QUICKQUERY_CLEAR_CONTEXT';
export const QUICKQUERY_CLEAR_RESULT = 'QUICKQUERY_CLEAR_RESULT';
export const QUICKQUERY_CLEAR_RESULT_ACTION = 'QUICKQUERY_CLEAR_RESULT_ACTION';

export const QUICKQUERY_SEND_REQUEST = 'QUICKQUERY_SEND_REQUEST';
export const QUICKQUERY_SEND_REQUEST_SUCCESS =
  'QUICKQUERY_SEND_REQUEST_SUCCESS';
export const QUICKQUERY_SEND_REQUEST_ERROR = 'QUICKQUERY_SEND_REQUEST_ERROR';

export const QUICKQUERY_SEND_ACTION_REQUEST = 'QUICKQUERY_SEND_ACTION_REQUEST';
export const QUICKQUERY_SEND_ACTION_REQUEST_SUCCESS =
  'QUICKQUERY_SEND_ACTION_REQUEST_SUCCESS';
export const QUICKQUERY_SEND_ACTION_REQUEST_ERROR =
  'QUICKQUERY_SEND_ACTION_REQUEST_ERROR';
// export const QUICKQUERY_UPDATE_IS_SYNCING = 'QUICKQUERY_UPDATE_IS_SYNCING';
