export const STOCKTAKE_LOAD_OFFLINE_STOCKTAKES_SUCCESS =
  'STOCKTAKE_LOAD_OFFLINE_STOCKTAKES_SUCCESS';
export const STOCKTAKE_GET_STOCKTAKES = 'STOCKTAKE_GET_STOCKTAKES';
export const STOCKTAKE_GET_STOCKTAKES_SUCCESS =
  'STOCKTAKE_GET_STOCKTAKES_SUCCESS';
export const STOCKTAKE_GET_STOCKTAKES_ERROR = 'STOCKTAKE_GET_STOCKTAKES_ERROR';
export const STOCKTAKE_LOAD_OFFLINE_LOCATIONS_SUCCESS =
  'STOCKTAKE_LOAD_OFFLINE_LOCATIONS_SUCCESS';
export const STOCKTAKE_GET_LOCATIONS = 'STOCKTAKE_GET_LOCATIONS';
export const STOCKTAKE_GET_LOCATIONS_SUCCESS =
  'STOCKTAKE_GET_LOCATIONS_SUCCESS';
export const STOCKTAKE_GET_LOCATIONS_ERROR = 'STOCKTAKE_GET_LOCATIONS_ERROR';
export const STOCKTAKE_SET_BRANCH = 'STOCKTAKE_SET_BRANCH';
export const STOCKTAKE_SET_LOCATION = 'STOCKTAKE_SET_LOCATION';
export const STOCKTAKE_GET_ROWS = 'STOCKTAKE_GET_ROWS';
export const STOCKTAKE_GET_ROWS_SUCCESS = 'STOCKTAKE_GET_ROWS_SUCCESS';
export const STOCKTAKE_GET_ROWS_ERROR = 'STOCKTAKE_GET_ROWS_ERROR';
export const STOCKTAKE_GET_PACKS = 'STOCKTAKE_GET_PACKS';
export const STOCKTAKE_GET_PACKS_SUCCESS = 'STOCKTAKE_GET_PACKS_SUCCESS';
export const STOCKTAKE_GET_PACKS_ERROR = 'STOCKTAKE_GET_PACKS_ERROR';
export const STOCKTAKE_UPDATE_INPUT = 'STOCKTAKE_UPDATE_INPUT';
export const STOCKTAKE_ADD_PACKS_TO_ROW = 'STOCKTAKE_ADD_PACKS_TO_ROW';
export const STOCKTAKE_ADD_PACK_TO_ROW = 'STOCKTAKE_ADD_PACK_TO_ROW';
export const STOCKTAKE_DELETE_PACK_FROM_ROW = 'STOCKTAKE_DELETE_PACK_FROM_ROW';
export const STOCKTAKE_ADD_ROW_TO_STOCKTAKE = 'STOCKTAKE_ADD_ROW_TO_STOCKTAKE';
export const STOCKTAKE_DELETE_ROW_FROM_STOCKTAKE =
  'STOCKTAKE_DELETE_ROW_FROM_STOCKTAKE';
export const STOCKTAKE_UPDATE_NEWROWINPUT = 'STOCKTAKE_UPDATE_NEWROWINPUT';
export const STOCKTAKE_UPDATE_PRECOUNTINPUT = 'STOCKTAKE_UPDATE_PRECOUNTINPUT';
export const STOCKTAKE_UPDATE_NEWLOCATIONINPUT =
  'STOCKTAKE_UPDATE_NEWLOCATIONINPUT';
export const STOCKTAKE_CREATE_ROW = 'STOCKTAKE_CREATE_ROW';
export const STOCKTAKE_CREATE_ROW_SUCCESS = 'STOCKTAKE_CREATE_ROW_SUCCESS';
export const STOCKTAKE_CREATE_ROW_ERROR = 'STOCKTAKE_CREATE_ROW_ERROR';
export const STOCKTAKE_DELETE_ROW = 'STOCKTAKE_DELETE_ROW';
export const STOCKTAKE_DELETE_ROW_SUCCESS = 'STOCKTAKE_DELETE_ROW_SUCCESS';
export const STOCKTAKE_DELETE_ROW_ERROR = 'STOCKTAKE_DELETE_ROW_ERROR';
export const STOCKTAKE_UPDATE_PACK = 'STOCKTAKE_UPDATE_PACK';
export const STOCKTAKE_UPDATE_PACK_SUCCESS = 'STOCKTAKE_UPDATE_PACK_SUCCESS';
export const STOCKTAKE_UPDATE_PACK_ERROR = 'STOCKTAKE_UPDATE_PACK_ERROR';
export const STOCKTAKE_EXPORT_PACKS = 'STOCKTAKE_EXPORT_PACKS';
export const STOCKTAKE_EXPORT_ROWS = 'STOCKTAKE_EXPORT_ROWS';
export const STOCKTAKE_EXPORT_DONE = 'STOCKTAKE_EXPORT_DONE';
export const STOCKTAKE_EXPORT_CLEAR = 'STOCKTAKE_EXPORT_CLEAR';
export const STOCKTAKE_CREATE_ROWS = 'STOCKTAKE_CREATE_ROWS';
export const STOCKTAKE_CREATE_ROWS_SUCCESS = 'STOCKTAKE_CREATE_ROWS_SUCCESS';
export const STOCKTAKE_CREATE_ROWS_ERROR = 'STOCKTAKE_CREATE_ROWS_ERROR';
export const STOCKTAKE_UPDATE_PACKS = 'STOCKTAKE_UPDATE_PACKS';
export const STOCKTAKE_UPDATE_PACKS_SUCCESS = 'STOCKTAKE_UPDATE_PACKS_SUCCESS';
export const STOCKTAKE_UPDATE_PACKS_ERROR = 'STOCKTAKE_UPDATE_PACKS_ERROR';
export const STOCKTAKE_GET_EXISTING_BINS = 'STOCKTAKE_GET_EXISTING_BINS';
export const STOCKTAKE_GET_EXISTING_BINS_SUCCESS =
  'STOCKTAKE_GET_EXISTING_BINS_SUCCESS';
export const STOCKTAKE_GET_EXISTING_BINS_ERROR =
  'STOCKTAKE_GET_EXISTING_BINS_ERROR';
export const STOCKTAKE_GET_PACKET_TALLY = 'STOCKTAKE_GET_PACKET_TALLY';
export const STOCKTAKE_GET_PACKET_TALLY_SUCCESS =
  'STOCKTAKE_GET_PACKET_TALLY_SUCCESS';
export const STOCKTAKE_GET_PACKET_TALLY_ERROR =
  'STOCKTAKE_GET_PACKET_TALLY_ERROR';
export const STOCKTAKE_GET_PRODUCT_GCS = 'STOCKTAKE_GET_PRODUCT_GCS';
export const STOCKTAKE_GET_PRODUCT_GCS_SUCCESS =
  'STOCKTAKE_GET_PRODUCT_GCS_SUCCESS';
export const STOCKTAKE_GET_PRODUCT_GCS_ERROR =
  'STOCKTAKE_GET_PRODUCT_GCS_ERROR';
export const STOCKTAKE_GET_OPTIONS = 'STOCKTAKE_GET_OPTIONS';
export const STOCKTAKE_GET_OPTIONS_SUCCESS = 'STOCKTAKE_GET_OPTIONS_SUCCESS';
export const STOCKTAKE_GET_OPTIONS_ERROR = 'STOCKTAKE_GET_OPTIONS_ERROR';
export const STOCKTAKE_CLEAR_ROW_BY_STOCKTAKE =
  'STOCKTAKE_CLEAR_ROW_BY_STOCKTAKE';
export const STOCKTAKE_CLEAR_PACKS_BY_STOCKTAKE =
  'STOCKTAKE_CLEAR_PACKS_BY_STOCKTAKE';
export const STOCKTAKE_GET_LOCATIONS_BY_STOCKTAKEID =
  'STOCKTAKE_GET_LOCATIONS_BY_STOCKTAKEID';
export const STOCKTAKE_GET_LOCATIONS_BY_STOCKTAKEID_SUCCESS =
  'STOCKTAKE_GET_LOCATIONS_BY_STOCKTAKEID_SUCCESS';
export const STOCKTAKE_GET_LOCATIONS_BY_STOCKTAKEID_ERROR =
  'STOCKTAKE_GET_LOCATIONS_BY_STOCKTAKEID_ERROR';
